#!/bin/bash

MNGMT_STATION=$1 # address
COMMUNITY_STRING=$2 # e.g public
HOST_NAME=$3 # string
SERVICE_DESCRIPTION=$4 # string
RETURN_CODE=$5 # integer
SERVICE_OUTPUT=$6 # string
SERVICE_GROUP_NAME=$7 # string
DURATION_SEC=$8 # integer
SERVICE_LAST_CHECK=$9 # integer
SERVICE_LAST_STATE_CHANGE=${10} # integer
SERVICE_ATTEMPT=${11}  # integer

if [[ -z "$MNGMT_STATION" || -z "$COMMUNITY_STRING" || -z "$HOST_NAME" || -z "$SERVICE_DESCRIPTION" || -z "$RETURN_CODE" || -z "$SERVICE_OUTPUT" || -z "$SERVICE_GROUP_NAME" || -z "$DURATION_SEC" || -z "$SERVICE_LAST_CHECK" || -z "$SERVICE_LAST_STATE_CHANGE" || -z "$SERVICE_ATTEMPT" ]]
then
   echo -e "Syntax error\nUsage: $0 <MNGMT_STATION> <COMMUNITY_STRING> <HOST_NAME> <SERVICE_DESCRIPTION> <RETURN_CODE> <SERVICE_OUTPUT> <SERVICE_GROUP_NAME> <DURATION_SEC> <SERVICE_LAST_CHECK> <SERVICE_LAST_STATE_CHANGE> <SERVICE_ATTEMPT>"
   exit 0
fi

/usr/bin/snmptrap -v 2c -c $COMMUNITY_STRING $MNGMT_STATION '' NAGIOS-NOTIFY-MIB::nSvcEvent nSvcHostname s "$HOST_NAME" nSvcDesc s "$SERVICE_DESCRIPTION" nSvcStateID i $RETURN_CODE nSvcOutput s "$SERVICE_OUTPUT" nSvcGroupName s "$SERVICE_GROUP_NAME" nSvcDurationSec i $DURATION_SEC nSvcLastCheck i $SERVICE_LAST_CHECK nSvcLastChange i $SERVICE_LAST_STATE_CHANGE nSvcAttempt i $SERVICE_ATTEMPT
